### ISSUE TITLE
Could you please release the training loss curve?

### ISSUE THREAD

**Issue by curiosity654** [mcahny/object_localization_network#8]
Thank you for the amazing work, however, when I train the model using default configs, the validation results are extremely low. Could you provide the training loss curve for comparison? Thanks in advance.
![image](https://user-images.githubusercontent.com/34833233/165429446-1b3bdedd-7754-4441-9e6c-49d7365234a2.png)
![image](https://user-images.githubusercontent.com/34833233/165429486-10b6d7d4-ab71-49a3-b122-c1b80232dd81.png)

**Comment by mcahny** [comment]
Thanks for your interest.

Let me share my old training curves and (tf)logs.
[tflog](https://drive.google.com/file/d/1TbsWt3MfrMFmQZoaIxoBH40oj0ikAT_W/view?usp=sharing)
[log](https://drive.google.com/file/d/1qxgpPZJj7hrKgyojyUA2o575MeEFbho5/view?usp=sharing)
![image](https://user-images.githubusercontent.com/19910190/165433101-48d716fc-b9ca-40ac-967d-3744c2425966.png)
