### ISSUE TITLE
About Cross Category Evaluation

### ISSUE THREAD

**Issue by curiosity654** [mcahny/object_localization_network#9]
Hi there, I have a question regarding cross-category evaluation. According to the code, the dataset filter out non-VOC annotations, but this does not filter out images. If the images contain other VOC classes, will they be included in the training set.
![image](https://user-images.githubusercontent.com/34833233/168761520-74ff6829-b907-4c7b-ba79-d04b3ba60579.png)

**Comment by wangchust** [comment]
Images only contain non-VOC categories will excluded in training stage. Details can be found in function _filter_imgs() of coco_split.py

ids_in_cat = set()
for i, class_id in enumerate(self.train_cat_ids):
            ids_in_cat |= set(self.coco.cat_img_map[class_id])

**Comment by curiosity654** [comment]
Thank you for the explanation! I got it now.
